### PR TITLE
[fix] Use new label for knative broker (needed for Serverless 1.11.0)

### PR DESCRIPTION
**Pull request by llowinge**
As described at https://docs.openshift.com/container-platform/4.6/serverless/event_workflows/serverless-using-brokers.html#serverless-using-brokers-creating-brokers

### CODE REVIEW

**Comment by llowinge** [comment]
@bouskaJ FYI

**Comment by llowinge** [comment]
@nicolaferraro Could you review/merge ?

**Comment by llowinge** [comment]
@oscerd Could you review/merge ?

**Comment by llowinge** [comment]
@astefanutti Could you review/merge ?

**Review by astefanutti — APPROVED** [review]

**Pull request merged**
